# Generated by Django 4.0.6 on 2022-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_p_name_product_name_remove_order_take_away_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='home_delivery',
            new_name='take_away',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Todayspl', 'Todays special')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
